import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { analyzeBoundaries } from "../../../src/analysis/boundaries.js";

let repoRoot = "";

beforeAll(async () => {
  repoRoot = await mkdtemp(path.join(os.tmpdir(), "test-steward-boundaries-"));
  await mkdir(path.join(repoRoot, "src/routes"), { recursive: true });
  await mkdir(path.join(repoRoot, "db/migrations"), { recursive: true });
  await mkdir(path.join(repoRoot, ".github/workflows"), { recursive: true });
  await mkdir(path.join(repoRoot, ".test-steward"), { recursive: true });
  await mkdir(path.join(repoRoot, "generated"), { recursive: true });

  await writeFile(
    path.join(repoRoot, "src/routes", "users.ts"),
    [
      'import express from "express";',
      "const app = express();",
      'app.get("/users/:id", getUser);',
      'app.post("/users", createUser);',
      "app.use(errorMiddleware);",
      'cache.get("users", refresh);',
    ].join("\n"),
  );

  await writeFile(
    path.join(repoRoot, "src/routes", "handlers.ts"),
    [
      "export async function GET() {}",
      "export function POST() {}",
      "function DELETE() {}",
    ].join("\n"),
  );

  await writeFile(
    path.join(repoRoot, "db/migrations", "001-add-users.sql"),
    "CREATE TABLE users;\n",
  );
  await writeFile(path.join(repoRoot, "db", "snapshot.sql"), "SELECT 1;\n");
  await writeFile(
    path.join(repoRoot, "src", "user.schema.ts"),
    'import { z } from "zod";\nexport const userSchema = z.object({});\n',
  );
  await writeFile(
    path.join(repoRoot, "src", "plain.ts"),
    "export const value = 1;\n",
  );
  await writeFile(path.join(repoRoot, "openapi.json"), "{}\n");
  await writeFile(
    path.join(repoRoot, "vite.config.ts"),
    "export default {};\n",
  );
  await writeFile(
    path.join(repoRoot, ".github/workflows", "ci.yml"),
    "on: push\n",
  );
  await writeFile(
    path.join(repoRoot, ".test-steward", "protected-tests.json"),
    "[]\n",
  );
  await writeFile(
    path.join(repoRoot, "generated", "client.ts"),
    "// Generated by protoc. Do not edit!\nexport const client = {};\n",
  );
});

afterAll(async () => {
  await rm(repoRoot, { recursive: true, force: true });
});

describe("boundary analysis", () => {
  it("finds route registrations with method and path", async () => {
    const { boundaries } = await analyzeBoundaries({
      repoRoot,
      files: ["src/routes/users.ts"],
    });
    const routes = boundaries.filter(
      (fact) => fact.kind === "route-registration",
    );
    // Sorted by (file, kind, path); `app.use(errorMiddleware)` has a non-literal
    // path and `cache.get("users", ...)` is not a router object — both excluded.
    expect(routes).toEqual([
      {
        file: "src/routes/users.ts",
        kind: "route-registration",
        path: "/users",
        method: "post",
      },
      {
        file: "src/routes/users.ts",
        kind: "route-registration",
        path: "/users/:id",
        method: "get",
      },
    ]);
  });

  it("finds exported HTTP handler functions and ignores non-exported ones", async () => {
    const { boundaries } = await analyzeBoundaries({
      repoRoot,
      files: ["src/routes/handlers.ts"],
    });
    expect(
      boundaries.filter((fact) => fact.kind === "route-handler-export"),
    ).toEqual([
      {
        file: "src/routes/handlers.ts",
        kind: "route-handler-export",
        path: "GET",
        method: "get",
      },
      {
        file: "src/routes/handlers.ts",
        kind: "route-handler-export",
        path: "POST",
        method: "post",
      },
    ]);
  });

  it("flags migration paths by directory, file name, and SQL extension", async () => {
    const { boundaries } = await analyzeBoundaries({
      repoRoot,
      files: ["db/migrations/001-add-users.sql", "db/snapshot.sql"],
    });
    const migrations = boundaries.filter((fact) => fact.kind === "migration");
    expect(migrations).toEqual([
      {
        file: "db/migrations/001-add-users.sql",
        kind: "migration",
        path: "migrations directory",
      },
      {
        file: "db/migrations/001-add-users.sql",
        kind: "migration",
        path: "SQL file",
      },
      { file: "db/snapshot.sql", kind: "migration", path: "SQL file" },
    ]);
  });

  it("flags schema/serialization files by path pattern and by library import", async () => {
    const { boundaries } = await analyzeBoundaries({
      repoRoot,
      files: ["src/user.schema.ts", "src/plain.ts", "openapi.json"],
    });
    const schema = boundaries.filter(
      (fact) => fact.kind === "schema-serialization",
    );
    expect(schema).toEqual([
      {
        file: "openapi.json",
        kind: "schema-serialization",
        path: "OpenAPI document",
      },
      {
        file: "src/user.schema.ts",
        kind: "schema-serialization",
        path: "*.schema.* file",
      },
      {
        file: "src/user.schema.ts",
        kind: "schema-serialization",
        path: "serialization library import",
        detail: "zod",
      },
    ]);
    expect(schema.some((fact) => fact.file === "src/plain.ts")).toBe(false);
  });

  it("flags configuration and deployment files by path", async () => {
    const { boundaries } = await analyzeBoundaries({
      repoRoot,
      files: [
        "vite.config.ts",
        ".github/workflows/ci.yml",
        ".test-steward/protected-tests.json",
      ],
    });
    const configs = boundaries.filter((fact) => fact.kind === "config");
    expect(configs).toEqual([
      { file: ".github/workflows/ci.yml", kind: "config", path: "CI workflow" },
      {
        file: ".test-steward/protected-tests.json",
        kind: "config",
        path: "test-steward configuration",
      },
      { file: "vite.config.ts", kind: "config", path: "config module" },
    ]);
  });

  it("flags generated code by content marker", async () => {
    const { boundaries } = await analyzeBoundaries({
      repoRoot,
      files: ["generated/client.ts"],
    });
    const generated = boundaries.filter(
      (fact) => fact.kind === "generated-code",
    );
    expect(generated).toContainEqual({
      file: "generated/client.ts",
      kind: "generated-code",
      path: "generated directory",
    });
    expect(generated).toContainEqual({
      file: "generated/client.ts",
      kind: "generated-code",
      path: "generated content marker",
    });
  });

  it("reports unreadable input files", async () => {
    const { boundaries, unreadableFiles } = await analyzeBoundaries({
      repoRoot,
      files: ["src/missing.ts"],
    });
    expect(boundaries).toEqual([]);
    expect(unreadableFiles).toEqual(["src/missing.ts"]);
  });
});
